version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: lab5
    restart: unless-stopped
    ports:
      - "3308:3306"  # Host port 3308 maps to container's MySQL port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab5
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

  # phpMyAdmin Web UI
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-lab5
    restart: always
    ports:
      - "8084:80"  # Access phpMyAdmin at http://localhost:8084
    environment:
      PMA_HOST: mysql             # Refers to the "mysql" service name
      MYSQL_ROOT_PASSWORD: root  # Must match MySQL root password

volumes:
  mysql_data:  # Named volume for MySQL data persistence
